// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SpH9GENNjeDfR1QygyTeoZh48Q5BdSE',
    appId: '1:550588140059:web:5dd675398a3ac97faac6be',
    messagingSenderId: '550588140059',
    projectId: 'cacauth-da55b',
    authDomain: 'cacauth-da55b.firebaseapp.com',
    storageBucket: 'cacauth-da55b.appspot.com',
    measurementId: 'G-2YY1H2F3S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5cNXw3VYX1tKgcZKy60sZBlNOl-xsHw',
    appId: '1:550588140059:android:54aa2cdba35f39d7aac6be',
    messagingSenderId: '550588140059',
    projectId: 'cacauth-da55b',
    storageBucket: 'cacauth-da55b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYCOtvIkLuCYeZDwJGu_fznTVMC_5psoM',
    appId: '1:550588140059:ios:9bbb0690d6416359aac6be',
    messagingSenderId: '550588140059',
    projectId: 'cacauth-da55b',
    storageBucket: 'cacauth-da55b.appspot.com',
    iosClientId: '550588140059-drr2i5f22550ib7vinv0ghsof2umpieu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCacProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYCOtvIkLuCYeZDwJGu_fznTVMC_5psoM',
    appId: '1:550588140059:ios:4ad3f96cadad6a5eaac6be',
    messagingSenderId: '550588140059',
    projectId: 'cacauth-da55b',
    storageBucket: 'cacauth-da55b.appspot.com',
    iosClientId: '550588140059-vtdia3np8gl9kmoar0uel8m246r4f201.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCacProject.RunnerTests',
  );
}
